### ISSUE TITLE
SASS Compilation Error

### ISSUE THREAD

**Issue by effao** [creativetimofficial/material-dashboard#107]
Change Detected...
material-dashboard.scss
--------------------
Compilation Error
Error: File "c:\wamp64\www\assets\scss\material-dashboard\mixins\social-buttons.scss" not found
        on line 18 of sass/c:\wamp64\www\assets\scss\material-dashboard.scss
>>  @import "material-dashboard/mixins/social-buttons.scss";

   ---------^

--------------------
Watching...
--------------------

**Comment by groovemen** [comment]
Hello @effao,

Thank you for using our products, I will ask you to download again the product, and try the same action to compile the SCSS because I checked in the downloadable archive and it looks good.

<img width="1018" alt="Screenshot 2019-12-13 at 10 57 47" src="https://user-images.githubusercontent.com/21063398/70787481-6c273f00-1d97-11ea-8021-094d544dcc9c.png">

*also, please let us know your product version.

Best, 
Stefan
