### ISSUE TITLE
input type file not identifiable 

### ISSUE THREAD

**Issue by exexzian** [creativetimofficial/material-dashboard#11]
input type file ui doesn't really help/suggest whether we have to select file or enter text.

Wouldn't it be better to offer something like dropzone or traditional file input style.

**Comment by alexandru-paduraru** [comment]
@exexzian thank you for the feedback. I understand your point, you can do something like this

```html
<div class="form-group is-empty is-fileinput">
            <input type="file" id="inputFile4" multiple="">
            <div class="input-group">
              <input type="text" readonly="" class="form-control" placeholder="Placeholder w/file chooser...">
                <span class="input-group-btn input-group-sm">
                  <button type="button" class="btn btn-fab btn-fab-mini">
                    <i class="material-icons">attach_file</i>
                  </button>
                </span>
            </div>
 </div>
```

Which is adding a button on the file input so it is more clear. Otherwise, you can use the PRO version where we have Jasny Library with file preview: http://demos.creative-tim.com/material-dashboard-pro/examples/forms/extended.html

Hope this helps you.

Best,
Alex

**Comment by exexzian** [comment]
thanks @alexandru-paduraru for giving the customization idea, with that reference I am customizing file input to have bit of traditional HTML file input UI

**Comment by exexzian** [comment]
closing the issue :smile:
