### ISSUE TITLE
dropdown list issue

### ISSUE THREAD

**Issue by jaisankargopal** [creativetimofficial/material-dashboard#110]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

I'm facing the dropdown list problem. Drop down list covering by the class="ct-chart"

 `<div class="btn-group">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Allocate Performer Group</button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Separated link</a>
        </div>
      </div>
    </div>
`
![image](https://user-images.githubusercontent.com/8012061/72126748-4770b800-3393-11ea-912b-6c44dd6dd500.png)

**Comment by groovemen** [comment]
Hello @jaisankargopal, 

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

** Please make sure that you have the latest version because we tested this behavior and it looks good
<img width="862" alt="Screenshot 2020-01-10 at 10 28 01" src="https://user-images.githubusercontent.com/21063398/72137802-2361a680-3394-11ea-97d4-a135c263a95d.png">

All the best,
Stefan
