### ISSUE TITLE
[Bug] scroll down bug for rtl

### ISSUE THREAD

**Issue by abbas-chawan** [creativetimofficial/material-dashboard#139]
### Version
2.1.2
### Reproduction link
https://gist.github.com/abbas-chawan/eafc47d72faa0147fcd6483af64345a6
### Operating System
windows
### Device
Laptop
### Browser & Version
chrome & 86.0.4240.198
### Steps to reproduce
open rtl page
scroll down
### What is expected?
it should scroll down 
### What is actually happening?
it is scrolling towards left side

---
### Additional comments
working fine on jsBin
chrome is popping  warnings

DevTools failed to load SourceMap: Could not load content for http://localhost:8081/jamia/webPortal/assets/css/material-dashboard-rtl.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://localhost:8081/jamia/webPortal/assets/css/dashboard-free.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

browser can't find the following files
material-dashboard-rtl-css.map
dashboard-free.css.map

**Comment by payambordbar** [comment]
This problem is related to the perfect-scrollbar package
To solve this problem, you must update this package to the latest version (current v1.5.0)
Then make the following changes in the line 23-27 material-dashboard.js file

![image](https://user-images.githubusercontent.com/45229646/104374194-c2385a00-5536-11eb-84da-92966ce749f1.png)
