### ISSUE TITLE
Input Select Style

### ISSUE THREAD

**Issue by hardzork** [creativetimofficial/material-dashboard#14]
First of all I would like to congratulate you on your great work. Secondly, I apologize for my English.

I'm having problems with the css style of my select inputs, where sometimes it's applied to the component and some not.

Below are two images where it shows exactly what is occurring.

<a href="https://ibb.co/mzHCmF"><img src="https://preview.ibb.co/nPAnLa/0000001.png" alt="0000001" border="0"></a>
<a href="https://ibb.co/dcyJRF"><img src="https://preview.ibb.co/e9ZsmF/0000002.png" alt="0000002" border="0"></a>

Could someone help me in this case?

PS. All scripts are being loaded by the application.
PS². I'm using AngularJS v.1.6.1.

**Comment by alexandru-paduraru** [comment]
@hardzork thank you for using our product. Please check our Angular version for Material Dashboard: https://github.com/creativetimofficial/material-dashboard-angular and you will see how we call all the elements on initialization of the page. You need to make sure you call the init of the selectpicker every time when you enter to that page, not just on the initialization of the app because Angular is getting the elements dynamically and it's adding them to your page.

We don't have selectpicker in the Free version. Did you include, a new library or you use the PRO? Here is the repo for the free and this is confusing me :D 

Best,
Alex
