### ISSUE TITLE
[Bug] Select HTML element and Upload HTML elements do not work as expected

### ISSUE THREAD

**Issue by tylerlazenby** [creativetimofficial/material-dashboard#143]
### Version
2.1.0
### Reproduction link
https://jsfiddle.net/v8c1j4zs/1/
### Operating System
Windows 10 Enterprise
### Device
PC
### Browser & Version
Chrome 89.0.4389.90
### Steps to reproduce
1. Make sure to include the selectpicker plugin included with the package
2. Add a card and card body
3. Add a select html element with the form-control and selectpicker classes
### What is expected?
To have the select picker replace the select statement
### What is actually happening?
The select picker is appearing below the actual select element with no options and the drop down icon below the title.

---

**Comment by groovemen** [comment]
Hello @byuilazenbyt,

Thank you for using our products, please let us know if you are using the free version or the premium one.
We are asking this because this plugin, as you can see in the [product's documentation](https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/plugins/select-bootstrap.html), the selectpicker is a Premium Component so you can use it after you purchase the product.
You will get the initialization script and the styling for it.
<img width="300" alt="Screenshot 2021-03-19 at 20 41 01" src="https://user-images.githubusercontent.com/21063398/111828365-db250900-88f3-11eb-8fc3-53e8b6114938.png">
Please let us know if we can help with any other details.

Best,
Creative Tim Staff

P.S. Remember to wash your hands before coding!
