### ISSUE TITLE
chars does not show up with multiple tabs

### ISSUE THREAD

**Issue by alperensahin** [creativetimofficial/material-dashboard#29]
I am using material tabs as page subcategories in which there are multiple chartist charts. The problem is that chars does not show up except for first active tab. It seems that width comes as 0.

**Comment by alexandru-paduraru** [comment]
@alperensahin the charts don't appear in the other tabs because the tabs come with "display:none" property, that means the javascript cannot see anything that is inside them, so the javascript doesn't see the charts. What you have to do is to initialize the charts again when the tab is switched. You can see when the tab is switched by using the tabs events from Bootstrap: http://getbootstrap.com/javascript/#tabs-events

So you basically add the init of the chart inside the shown.bs.tab event, because that event is triggered as soon as the tab was completely shown.

Hope this helps!

**Comment by alperensahin** [comment]
thanks for fast response. It worked!

**Comment by AntonioBusillo** [comment]
Hi @alexandru-paduraru I'm trying to add a chart under a tab-pane using two different components like this:

`<div class="tab-pane" id="link3">
            <my-component></my-component>
            </div>`

I don't understand where I need to put the Javascript code you linked two years ago. Can you help me?

**Comment by groovemen** [comment]
Hello @AntonioBusillo, 

Thank you for using our products, the code from above (http://getbootstrap.com/javascript/#tabs-events) is for Bootstrap 3, if you are using the Bootstrap 4 version please let us know. 

Best, 
Stefan

**Comment by AntonioBusillo** [comment]
Yes, I'm using Bootstrap 4, with the angular version of the Material Dashboard (version 2.2.0)

**Comment by groovemen** [comment]
So, I will ask you to open this issue on the right repo (for the angular) https://github.com/creativetimofficial/material-dashboard-angular2 and my colleague will help you to solve your issue. 

All the best, 
Stefan
