### ISSUE TITLE
Can't get datepicker to show in a modal

### ISSUE THREAD

**Issue by rykr** [creativetimofficial/material-dashboard#32]
I've tried adding this to my css
.datepicker {
    z-index: 1151 !important;
}

and it didn't help.  Any idea why this isn't working?

**Comment by alexandru-paduraru** [comment]
@rykr thank you for using our product. Please make sure you initialize the datepicker after the Modal is shown, you can find the action triggered after the modal is shown here: https://getbootstrap.com/docs/3.3/javascript/#modals-events Otherwise the datepicker cannot be initialized because the Modal has `display:none` property as the default state.

Hope this helps.

Best,
alex
