### ISSUE TITLE
Datetimepicker popup doesn't open

### ISSUE THREAD

**Issue by NAWAZUDDIN552** [creativetimofficial/material-dashboard#83]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by zambianchi** [comment]
The problem is that this type of element is supported by the pro version of the template. If you compare the version of the datepicker script used in the pro version, with the original version, you will notice that there are some changes in the script. In fact, importing the pro version script instead of the original one (only the datetime picker), works.

This is because some styles of the datetimepicker have been modified that do not allow them to be viewed except with the modified script.
