### ISSUE TITLE
scroll down bug

### ISSUE THREAD

**Issue by nightw0lv** [creativetimofficial/material-dashboard#90]
scrolldown bug when screen is from phone

**Comment by groovemen** [comment]
Hello @nightw0lv,

Thank you for using our products, I will ask you to give us more details about your issue. 

Regards, 
Stefan

**Comment by Alexpress94** [comment]
Same here. It doesn't scroll to the very bottom on some devices. This happens in every route. In order to reproduce the error you can set the iPad from the inspector, zoom in and then try to scroll. It will scroll, but not to the bottom of the page. If anyone knows how to fix it, please tell us, 'cause my hair is falling like autumn leaves
