### ISSUE TITLE
select bar

### ISSUE THREAD

**Issue by MarcoOvidi** [creativetimofficial/material-dashboard#94]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Passing hover Logout and Setting button in Profile menu in Nav Bar they should be colored

# Current Behavior
Only Profile button become colored on mouse hover

# Failure Information (for bugs)

This is the section i'm talking about:

` <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <a class="dropdown-item" href="#">Profile</a>
                  <a class="dropdown-item" href="#">Settings</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Log out</a>
       </div>`

## Steps to Reproduce
Go on the last image of navbar , click and try to drag mouse hover profile , setting and logout

## Context

Your downloaded directory of the project is running in localhost

## Failure Logs
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35470053/52357480-86391800-2a36-11e9-9d63-2d2f27fd7bdc.gif)

**Comment by groovemen** [comment]
Hello @MarcoOvidi,

Thank you for using our products and for letting us know about this issue, a quick solution to solve it would be to change some properties for the fixed-plugin. 

So, I will ask you to do the following changes:
- instead of **opacity** property, you have to overwrite with **display** property
from this: 
<img width="301" alt="screenshot 2019-02-07 at 09 52 46" src="https://user-images.githubusercontent.com/21063398/52397887-c4c6e500-2abf-11e9-9bd4-b0a64e5d67da.png">
to this:
<img width="301" alt="screenshot 2019-02-07 at 09 53 13" src="https://user-images.githubusercontent.com/21063398/52397899-d0b2a700-2abf-11e9-8149-ca88f466ecbf.png">

This changes will solve this issue 
<img width="389" alt="screenshot 2019-02-07 at 10 01 27" src="https://user-images.githubusercontent.com/21063398/52397925-e758fe00-2abf-11e9-91c4-88659c1cea22.png">

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by MarcoOvidi** [comment]
Thx you , ASAP I will inform you about the situation.

Il giorno gio 7 feb 2019 alle 09:06 Stefan <notifications@github.com> ha
scritto:
